Migrate from HTTPX to HTTPXYZ (#39)
Concerns have been raised about the governance and future of the HTTPX
project. HTTPX has not released Python 3.13 support and has not done a
release of any kind since 2024. The reasons for this, and the path
forward, are confusing and controversial
([encode/httpx#3344](https://github.com/encode/httpx/discussions/3344)).
Issues and discussions were disabled
([encode/httpx#3784](https://github.com/encode/httpx/discussions/3784)),
citing "skewed gender representation," making further discussion
difficult.

Community members volunteered to
[fork HTTPX](https://httpxyz.org/why-fork/) to help alleviate some of
these difficulties and move forward.

This PR will migrate from HTTPX to the [HTTPXYZ](https://httpxyz.org/)
fork.

In many cases, the migration can be accomplished with simply
`import httpxyz as httpx`, or just `import httpxyz` and updating
references in those modules to point to the `httpxyz` namespace.

In some specific cases, third-party dependencies rely on HTTPX
specifically for their internal functionality, such as the
[FastAPI/Starlette `TestClient`](https://fastapi.tiangolo.com/tutorial/testing/)
and the [RESPX](https://lundberg.github.io/respx/) HTTPX test mocking
package. Installing HTTPXYZ 0.28.2 raises an error:

```
ERROR tests/test_fastapi.py
RuntimeError: The starlette.testclient module requires the httpx package to be installed.
You can install this with:
    $ pip install httpx
```

In these cases, HTTPXYZ will need to have more precise drop-in
compatibility with HTTPX. A strategy for achieving this drop-in
compatibility is `sys.modules.setdefault`, which can replace a module's
namespace with that of another module. HTTPXYZ uses this strategy
(`sys.modules.setdefault("httpx", _sys.modules[__name__])`). As long as
HTTPXYZ is imported before other dependencies that require HTTPX, it
will just work.

- https://github.com/br3ndonland/fastenv/pull/35
- https://github.com/encode/httpx/discussions/3344
- [HTTPXYZ docs: Why we forked HTTPX](https://httpxyz.org/why-fork/)
- [HTTPXYZ Codeberg](https://codeberg.org/httpxyz/httpxyz)
- [httpxyz/httpxyz#18](https://codeberg.org/httpxyz/httpxyz/pulls/18)
- [Michiel Beijen Blog 2026-03-25: Why I forked httpx](https://tildeweb.nl/%7Emichiel/httpxyz.html)
- [Changelog News 184 2026-03-27](https://changelog.com/news/184)